apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: workshop
  name: http-doom
  labels:
    app: http-doom

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app: http-doom

  template:
    metadata:
      labels:
        app: http-doom
      annotations:
    spec:
      containers:
        - image: gcr.io/unity-ads-workshop-test/http-doom:master
          name: http-doom
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 0.1
              memory: 128Mi
            limits:
              cpu: 0.5
              memory: 1024Mi
          env:
            - name: PORT
              value: "8080"

      nodeSelector:
        cloud.google.com/gke-nodepool: workshop-pool