kind: Service
apiVersion: v1
metadata:
  labels:
    app: http-doom
  name: http-doom
  namespace: workshop

spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: http-doom